export const INCREMENT_SEQUENCE = "INCREMENT_SEQUENCE";
export const SET_CURRENT = "SET_CURRENT";
export const SET_PLAYER_SEQUENCE = "SET_PLAYER_SEQUENCE"
export const RESET_PLAYER_SEQUENCE = "RESET_PLAYER_SEQUENCE"
export const RESET_GAME = "RESET_GAME"